PlantUML
@startuml
title Scheduler Domain
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
hide circle
'hide members
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
'skinparam monochrome true
skinparam packageStyle frame

package Helper {
class Error{
type
lesson
}
class Alert{
type
lesson
}

class Expert{
id
load()
handling()
save()
publish()
}
class Schedule{
id
year
term
load()
}
class Lesson{
number
type
'face-to-face
begin
finish
'week
'day
load()
}
class Teacher{
id
workload
e-mail
}
class Discipline{
id
workload
}
class Pair {
id
begin
ending
}
'class Student{
'id
'e-mail
'}
class Group{
id
}
class Building {
name
}
class Auditorium {
name
}
'class Transfer {
'route
'time
'}
Expert -"*" Schedule
Alert "*"-- Lesson
Lesson --Teacher
Group "*"-- Lesson
Schedule -"*" Lesson
Lesson --"*" Error
Lesson -- Discipline
Pair "*"-- Lesson
Building -- Auditorium
Lesson - Auditorium
'Building "2"-"1" Transfer
'Group -"*" Student
'Lesson --Transfer
@enduml

Смысл терминов:
Alert - Предупреждение
Error – Ошибка
Schedule - Расписание
   term - семестр
Lesson – Занятие
   face-to -face - очное
Pair -  Пара
Group - Группа
Student - Студент
Building  - Корпус
Auditorium - Аудитория
Transfer  - Трансфер
Route – маршрут
Discipline - Дисциплина
Teacher - Преподаватель
Expert - Эксперт
    handling - обработка






