PlantUML
@startuml
title Scheduler Domain
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
hide circle
'hide members
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
'skinparam monochrome true
skinparam packageStyle frame

package Handler {
class Error{
name
lesson
}
class Alert{
name
lesson
}

class Expert{
name
load()
handling()
save()
publish()
}
class Schedule{
name
year
term
week_1_date
load()
}
class Lesson{
name
type
'face-to-face
begin
finish
'week
'day
load()
}
class Teacher{
name
e-mail
}
class Discipline{
name
workload
}
class Pair {
date
begin
finish
}
'class Student{
'id
'e-mail
'}
class Group{
name
students
}
'class Building {
'name
'}
class Auditorium {
name
address
}
'class Transfer {
'route
'time
'}
Expert -"*" Schedule
Schedule -"*" Lesson
Alert "*"-- Lesson
Lesson --Teacher
Group "*"-- Lesson
Lesson --"*" Error
Lesson -- Discipline
Pair "*"-- Lesson
Lesson - Auditorium
'Building -- Auditorium
'Building "2"-"1" Transfer
'Group -"*" Student
'Lesson --Transfer
@enduml

Смысл терминов:
workload - нагрузка
Alert - Предупреждение
Error – Ошибка
Schedule - Расписание
   term - семестр
Lesson – Занятие
   face-to-face - очное
Pair -  Пара
Group - Группа
Student - Студент
Building  - Корпус
Auditorium - Аудитория
Transfer  - Трансфер
Route – маршрут
Discipline - Дисциплина
Teacher - Преподаватель
Expert - Эксперт
    handling - обработка
Route – маршрут





