PlantUML
@startuml
title Scheduler Domain
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
hide circle
'hide members
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
'skinparam monochrome true
skinparam packageStyle frame

package Handler {

class UndesirableEffect{
name
kind
[les_1, les_2]
find()
}
class SeminarBeforeLecture{
name
kind
[les_1, les_2]
find()
}
class ManyLecturesInOneDay{
name
kind
[les_1, les_2]
find()
}
class Expert{
name
load()
handling()
save()
publish()
}
class Schedule{
name
year
term
load()
find_ue()
}
class Lesson{
week
day
pair
kind
number
load()
}
class Teacher{
name
'e-mail
}
class Discipline{
name
'workload
}
'class Pair {
'id
'begin
'finish
'}
'class Student{
'id
'e-mail
'}
class Group{
name
'students
}
'class Building {
'name
'}
class Auditorium {
name
'address
}

Expert -"*" Schedule
Schedule -"*" Lesson
UndesirableEffect "*"--Schedule
Group "*"-- Lesson
SeminarBeforeLecture --|> UndesirableEffect
Lesson --Teacher
ManyLecturesInOneDay --|> UndesirableEffect
Lesson -- Discipline
'Pair "*"-- Schedule
Auditorium  --  Lesson
'Building -- Auditorium
'Building "2"-"1" Transfer
'Group -"*" Student
'Lesson --Transfer
@enduml

Смысл терминов:
workload - нагрузка
UndesirableEffect - Предупреждение
Error – Ошибка
Schedule - Расписание
   term - семестр
Lesson – Занятие
   face-to-face - очное
Pair -  Пара
Group - Группа
Student - Студент
Building  - Корпус
Auditorium - Аудитория
Transfer  - Трансфер
Route – маршрут
Discipline - Дисциплина
Teacher - Преподаватель
Expert - Эксперт
    handling - обработка
Route – маршрут





