PlantUML
@startuml
title Scheduler Domain
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
hide circle
'hide members
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
'skinparam monochrome true
skinparam packageStyle frame

package Handler {

class UndesirableEffect{
name
kind
[les_1, les_2]
find()
}
class SeminarBeforeLecture{
}
class ManyLecturesInOneDay{
}
class Expert{
name
teachers
groups
load()
handling()
save()
publish()
}
class Schedule{
name
year
term
weeks
days
pairs
load()
find_ue()
}
class Lesson{
week
day
pair
type
theme
teacher
groups
auditorium
load()
}
class Teacher{
name
'e-mail
}
class Course{
name
lectures
seminars
'workload
}
class Pair {
name
begin
finish
'}
'class Student{
'id
'e-mail
}
class Group{
beg_year
name
students
'students
}
class Transfer {
name
}
class Building {
name
}
class Auditorium {
name
students
'address
}
class Theme{
type
number
ac_hour
}

Expert -"*" Schedule
Schedule -"*" Lesson
UndesirableEffect "*"--Schedule
SeminarBeforeLecture --|> UndesirableEffect
ManyLecturesInOneDay --|> UndesirableEffect
Schedule --"*" Course
Group "*"-Teacher
Pair "*"-- Lesson
Course -"*" Theme
Auditorium "*"- Expert
Teacher "*"- Course
Transfer "1"--"2" Building
Building --"*" Auditorium
'Group -"*" Student
@enduml

Смысл терминов:
workload - нагрузка
UndesirableEffect - Предупреждение
Error – Ошибка
Schedule - Расписание
   term - семестр
Lesson – Занятие
   face-to-face - очное
Pair -  Пара
Group - Группа
Student - Студент
Building  - Корпус
Auditorium - Аудитория
Transfer  - Трансфер
Route – маршрут
Course - Рабочая программа
Teacher - Преподаватель
Expert - Эксперт
    handling - обработка
Route – маршрут