PlantUML
@startuml
title Scheduler Domain
skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
hide circle
'hide members
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
'skinparam monochrome true
skinparam packageStyle frame


package Handler {
'note "Spread:\n Ask & Bid\n lots in deal" as spread
class UndesirableEffect{
name
rating
[les_1, les_2]
find()
}
class SeminarBeforeLecture{
}
class ManyLecturesInOneDay{
}
'class UeReport{
'desirability
'create()
'save()
'publish()
'}
class University{
name
create()
load()
handling()
save()
publish()
}
class Schedule{
name
year
term_number
week_numbers
week_days
pair_numbers
load()
save()
}
class Lesson{
week
day
'pair
type
teacher
groups
auditorium
}
class Teacher{
name
types
'active
'e-mail
}
class Course{
name
lectures
seminars
}
class Pair {
name
begin
finish
'}
'class Student{
'id
'e-mail
}
class Group{
beg_year
name
'active
students
'students
}
class Transfer {
name
'active
}
class Building {
name
'active
}
class Auditorium {
name
'active
students
'address
}
class Theme{
type
number
ac_hour
}

University -"*" Schedule
Schedule -"*" Lesson
University --"*"Group
University --"*" Teacher
UndesirableEffect "*"--Schedule
SeminarBeforeLecture --|> UndesirableEffect
ManyLecturesInOneDay --|> UndesirableEffect
'UeReport -- Schedule
'UndesirableEffect "*" - UeReport
Schedule --"*" Course
Group "*"-Teacher
Lesson -- Theme
Pair "*"-- Lesson
Course -"*" Theme
Auditorium "*"- University
Teacher "*"- Course
Transfer "1"--"2" Building
Building --"*" Auditorium
'Group -"*" Student
@enduml

Смысл терминов:
workload - нагрузка
UndesirableEffect - Предупреждение
Error – Ошибка
Schedule - Расписание
   term - семестр
Lesson – Занятие
   face-to-face - очное
Pair -  Пара
Group - Группа
Student - Студент
Building  - Корпус
Auditorium - Аудитория
Transfer  - Трансфер
Route – маршрут
Course - Рабочая программа
Teacher - Преподаватель
    kinds - lector, assistant
University - ВУЗ
    handling - обработка
Route – маршрут
